groups:
  - name: cargo
    key: c
    groups:
      - name: Tests
        key: t
        tasks:
          - name: All
            key: a
            cmd: cargo test -q
            confirm: true
            clear: true
          - name: Lib
            key: l
            cmd: cargo test -q --lib -p pmem
            confirm: true
            clear: true
