use crate::page::Page;
use binrw::BinRead;
use binrw::BinWrite;
use binrw::BinWriterExt;
use std::any::Any;
use std::any::TypeId;
use std::cell::Ref;
use std::cell::RefCell;
use std::cell::RefMut;
use std::collections::HashMap;
use std::fmt::Debug;
use std::marker::PhantomData;
use std::{io::Cursor, mem, rc::Rc};
use thiserror::Error;

const START_ADDR: usize = 4;

struct Allocator {
    page: Page,
    offset: usize,
}

#[derive(Error, Debug)]
enum Error {
    #[error("Pointer already initialized")]
    AlreadyInitialized,
}

impl Allocator {
    fn from(page: Page) -> Self {
        Self {
            page,
            offset: START_ADDR,
        }
    }

    fn new() -> Self {
        Self {
            page: Page::new(),
            offset: START_ADDR,
        }
    }

    fn alloc_untyped(&mut self, size: usize) -> Addr {
        assert!(size > 0);
        let addr = self.offset;
        self.offset += size;
        addr as u32
    }

    fn into(self) -> Page {
        self.page
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_allocation() {
        let mut allocator = Allocator::new();
        let mut page = Page::new();
        let a_ptr = {
            let mut scope = Scope::open(&mut allocator, &mut page);

            let a = scope.new(ListNode {
                value: 42,
                next: Ptr::null(),
            });
            a.ptr()
        };

        let mut scope = Scope::open(&mut allocator, &mut page);
        let handle = scope.lookup(a_ptr);
        assert_eq!(RefCell::borrow(&handle.value).value, 42);
    }

    #[test]
    fn allocate_simple_value() {
        let mut allocator = Allocator::new();
        let mut page = Page::new();
        let mut scope = Scope::open(&mut allocator, &mut page);

        let mut a = scope.new(ListNode {
            value: 35,
            next: Ptr::null(),
        });
        let mut b = scope.new(ListNode {
            value: 35,
            next: Ptr::null(),
        });

        a.as_mut().next = b.ptr();
        b.as_mut().next = a.ptr();
    }

    #[test]
    fn new_linked_list() {
        let mut allocator = Allocator::new();
        let mut page = Page::new();

        let scope = Scope::open(&mut allocator, &mut page);

        let mut list = LinkedList::new(scope);
        list.push(12);

        // let list = LinkedList::new(scope);
        assert_eq!(list.len(), 1);
    }
}

#[derive(BinRead, BinWrite)]
struct Ptr<T> {
    addr: u32,
    _phantom: PhantomData<T>,
}

impl<T> Clone for Ptr<T> {
    fn clone(&self) -> Self {
        *self
    }
}

/// Need to implement Copy manually, because derive(Copy) is automatically
/// adding `T: Copy` bound in autogenerated implementation
impl<T> Copy for Ptr<T> {}

impl<T> Ptr<T> {
    fn from_addr(addr: u32) -> Ptr<T> {
        Ptr {
            addr,
            _phantom: PhantomData::<T>,
        }
    }

    fn null() -> Self {
        Self::from_addr(0)
    }

    fn is_null(&self) -> bool {
        self.addr == 0
    }
}

fn borrow_downcast<T: Any>(cell: &RefCell<dyn Any>) -> Option<Ref<T>> {
    let r = cell.borrow();
    if (*r).type_id() == TypeId::of::<T>() {
        Some(Ref::map(r, |x| x.downcast_ref::<T>().unwrap()))
    } else {
        None
    }
}

struct LinkedList<'a> {
    scope: Scope<'a>,
    root: Ptr<ListNode>,
}

#[derive(BinRead, BinWrite, Clone)]
#[brw(little)]
struct ListNode {
    value: i32,
    next: Ptr<ListNode>,
}

impl ServiceEntity for ListNode {
    fn size(&self) -> usize {
        8
    }

    fn write_to(&self, buffer: &mut [u8]) {
        let mut cursor = Cursor::new(buffer);
        self.write(&mut cursor).unwrap();
    }
}

impl<'a> LinkedList<'a> {
    fn new(scope: Scope<'a>) -> Self {
        Self {
            scope,
            root: Ptr::from_addr(0),
        }
    }

    fn push(&mut self, value: i32) {
        let handle = self.scope.new(ListNode {
            value,
            next: Ptr::null(),
        });
        self.scope.write(&handle);
        self.root = handle.ptr();
    }

    fn len(&self) -> usize {
        let mut node: Ptr<_> = self.root;
        let mut len = 0;
        while !node.is_null() {
            len += 1;
            node = self.scope.lookup(node).as_ref().next;
        }
        len
    }
}

struct Utf8<'a> {
    data: &'a str,
}

type Addr = u32;

struct Scope<'a> {
    allocator: &'a mut Allocator,
    page: &'a mut Page,
    active_set: RefCell<HashMap<Addr, Rc<RefCell<dyn Any>>>>,
}

impl<'a> Scope<'a> {
    fn open(allocator: &'a mut Allocator, page: &'a mut Page) -> Self {
        Self {
            allocator,
            page,
            active_set: RefCell::new(HashMap::new()),
        }
    }

    fn lookup<T: BinRead + 'static>(&'a self, ptr: Ptr<T>) -> Handle<T>
    where
        T::Args<'a>: Default,
    {
        use binrw::BinReaderExt;

        let addr = ptr.addr as usize;
        let size = u32::from_ne_bytes(self.page.read_bytes::<4>(addr)) as usize;
        let bytes = self.page.as_bytes_uncommited((addr + 4)..(addr + 4 + size));
        let mut cursor = Cursor::new(bytes);
        let value: T = cursor.read_ne().unwrap();

        Handle {
            addr: addr as u32,
            value: Rc::new(RefCell::new(value)),
        }
    }

    fn new<T: ServiceEntity>(&mut self, value: T) -> Handle<T> {
        let size = value.size() + 4; // 4 bytes in size
        let addr = self.allocator.alloc_untyped(size);
        let addr_u = addr as usize;
        let sz = self.page.as_bytes_mut(addr_u..addr_u + size);
        sz[0..4].copy_from_slice(&(size as u32).to_ne_bytes());

        value.write_to(&mut sz[4..]);

        Handle {
            addr: addr as u32,
            value: Rc::new(RefCell::new(value)),
        }
    }

    fn change<T>(&self, ptr: Ptr<T>, f: impl Fn(&mut T)) {}

    fn finish(&self) {
        todo!()
    }

    fn write<T: ServiceEntity>(&mut self, handle: &Handle<T>) {
        let entity = RefCell::borrow(&handle.value);
        let size = entity.size() + 4;
        let bytes = self
            .page
            .as_bytes_mut(handle.addr as usize..handle.addr as usize + (size as usize));
        let (header, body) = bytes.split_at_mut(4);
        let mut cursor = Cursor::new(header);
        cursor.write_ne(&(size as u32)).unwrap();
        entity.write_to(body);
    }
}

struct Handle<T> {
    addr: Addr,
    value: Rc<RefCell<T>>,
}

impl<T> Handle<T> {
    fn as_mut(&mut self) -> RefMut<T> {
        RefCell::borrow_mut(&self.value)
    }

    fn as_ref(&self) -> Ref<T> {
        RefCell::borrow(&self.value)
    }

    fn ptr(&self) -> Ptr<T> {
        Ptr {
            addr: self.addr,
            _phantom: PhantomData::<T>,
        }
    }
}

impl<T: Debug + ServiceEntity + 'static> Handle<T> {
    fn join_handle(&self) -> Box<dyn JoinHandle> {
        Box::new(HandleImpl(Some(Rc::clone(&self.value))))
    }
}

struct HandleImpl<T>(Option<Rc<RefCell<T>>>);

impl<T: Debug + ServiceEntity + 'static> JoinHandle for HandleImpl<T> {
    fn join(&mut self) -> Option<Box<dyn ServiceEntity>> {
        let v = self.0.take().unwrap();
        let entity = Rc::try_unwrap(v).unwrap().into_inner();
        Some(Box::new(entity))
    }
}

trait ServiceEntity {
    fn size(&self) -> usize;
    fn write_to(&self, buffer: &mut [u8]);
}

trait JoinHandle {
    fn join(&mut self) -> Option<Box<dyn ServiceEntity>>;
}
