name: Benchmarks

on: pull_request

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          path: baseline-branch
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-export

      - name: Building Benchmarks
        run: |
          cargo export target/benchmarks -- bench --bench=page
          cargo export target/benchmarks -- bench --bench=rfs
          cd baseline-branch
          cargo export target/benchmarks -- bench --bench=page
          cargo export target/benchmarks -- bench --bench=rfs

      - name: Run Benchmarks
        run: |
          set -eo pipefail

          cat /dev/null > target/benchmark.txt
          target/benchmarks/page --color=never compare baseline-branch/target/benchmarks/page \
            -v -t 1 --fail-threshold 10 | tee -a target/benchmark.txt
          target/benchmarks/rfs --color=never compare baseline-branch/target/benchmarks/rfs \
            -v -t 1 --fail-threshold 10 | tee -a target/benchmark.txt

      - uses: actions/upload-artifact@v3
        with:
          name: benchmark.txt
          path: target/benchmark.txt
